# Generated by Django 2.1.1 on 2019-02-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('freq', models.CharField(choices=[('One time', 'One time'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly')], max_length=50)),
                ('file', models.FileField(upload_to='uploads/tasks/files')),
                ('desc', models.TextField()),
            ],
        ),
    ]
