# Generated by Django 2.1.1 on 2019-02-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
