# Generated by Django 2.1.1 on 2019-02-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_auto_20190222_0445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
