# Generated by Django 2.1.1 on 2019-02-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_delete_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tasks/files'),
        ),
        migrations.AlterField(
            model_name='event',
            name='freq',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('One time', 'One time')], max_length=50),
        ),
    ]
