# Generated by Django 2.1.1 on 2019-03-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0006_auto_20190228_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='freq',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('One time', 'One time')], max_length=50),
        ),
    ]
