# Generated by Django 2.1.1 on 2019-03-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0007_auto_20190304_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='freq',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('One time', 'One time')], max_length=50),
        ),
    ]
