# Generated by Django 2.1.1 on 2019-03-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0010_auto_20190304_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='freq',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('One time', 'One time')], max_length=50),
        ),
    ]
