# Generated by Django 2.1.1 on 2019-02-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album_Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='uploads/organizer/photos'),
        ),
    ]
