# Generated by Django 2.1.1 on 2019-03-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album_Organizer', '0002_auto_20190221_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
    ]
