# Generated by Django 2.1.1 on 2019-03-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album_Organizer', '0003_remove_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='Album_Organizer/static/images'),
        ),
    ]
